### PR TITLE
[FIX] DataView: correct HTML for nested lists

### PR DESCRIPTION
**Pull request by SeeSharpSoft**
Changed nested list DOMTree for DataView from \<ul>\<ul />\</ul> to \<ul>\<li>\<ul />\</li>\</ul>.

Permitted contents for an **ul** element are zero or more **li** elements (http://www.w3.org/TR/html-markup/ul.html).

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/SAP/ui5-inspector/pull/25" target="_blank">ReviewNinja

**Comment by Chariyski** [comment]
Hi @SeeSharpSoft,

Thank you for all the contributions!
I've reviewed the pull request and I like it, but your pull request will break the build due to some trailing white spaces ( https://travis-ci.org/SAP/ui5-inspector/builds/83457410 )

When I've created the travis build I didn't know that a script in the 'after_scrip' will not break the build. Yesterday I've fixed this issue with https://github.com/SAP/ui5-inspector/pull/28.

I'm sorry for the inconvenience, but you will need to update your pull request and remove the trailing spaces. After that I will be able to merge your pull request.

Best regards,
Krasimir

**Comment by SeeSharpSoft** [comment]
Hi Krasimir,

no problem, I just amended the changes to commit.

The other two pull requests I created rely on this change. I don't know what is best way to handle those commits. Rebasing when this fix was merged and a creating new pull request - or amend? Is it meant to create a pull request only for independent changes?

Best regards,
Martin

**Comment by Chariyski** [comment]
HI Martin,

For me personally it seems easier to rebase the other 2 contributions after this pull request is merged.

One more think - this branch is out-of-date with the base branch and you will need to update it, else I can't merge it.

Thanks and Best Regards,
Krasimir

**Pull request merged**
