### PR TITLE
[FIX] DataView: toggleCollapse only if arrow tag is a direct child

### PR DESCRIPTION
**Pull request by SeeSharpSoft**
This commit fixes an issue that makes a parent section expandable if any child element is expandable.

image
Clicking in the yellow area collapses the whole section cause the homeIcon entry is marked as expandable...

image
... even though the main section itself is not marked as expandable (no arrow).

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/SAP/ui5-inspector/pull/27" target="_blank">ReviewNinja

**Comment by kazandjiev** [comment]
Hi @SeeSharpSoft 
I tried to update your branch and merge it but you have to accept the licence/cla.

**Comment by SeeSharpSoft** [comment]
Hi,

I don't see the **Details** link for the licence/cla where I can agree to it. I just linked the forked repo in the CLA assistant. Anything else I need to do?

**Comment by SeeSharpSoft** [comment]
I just forced a push to the branch to trigger a new check...

**Comment by Chariyski** [comment]
Thank you :+1:

**Pull request merged**
