### PR TITLE
[INTERNAL] Update manifest version

### PR DESCRIPTION
**Pull request by Chariyski**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/SAP/ui5-inspector/pull/37" target="_blank">ReviewNinja

**Comment by matz3** [comment]
@Chariyski the `package.json` should be adopted as well, right?

**Comment by Chariyski** [comment]
@matz3 No need at this point. I will try to release without the xmake.

**Comment by matz3** [comment]
I mean just for consistency, as it's on `0.9.0` there. Otherwise it might confuse if the versions differ.

**Comment by Chariyski** [comment]
If everything is O.K. I will change the version of the package.json with a version that is not related to the WebStore.

Otherwise we will need to change it every time a new version is available, which is one more unneeded step.

**Pull request merged**
