### PR TITLE
Correct license badge

### PR DESCRIPTION
**Pull request by matz3**
@Chariyski I guess this is what you wanted to have. The current one is based on a Erlang project (https://hex.pm/packages/plug).

"https://img.shields.io/github/license/..." seems to be unresponsive atm, and as I guess the license won't change, this custom badge should be fine.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/SAP/ui5-inspector/pull/11" target="_blank">ReviewNinja

**Comment by Chariyski** [comment]
Thanks Matthias.

Btw check the download link :)

**Comment by matz3** [comment]
Already installed :+1: 
Great to see that the font is now fixed on OS X :smile:

**Comment by Chariyski** [comment]
xaxa :D ;)

**Pull request merged**
